# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47ba92476ea73bd31a195010d3dcde28816e25c29048f90b91c12757f7af62db63f9bcceaf5aef89e26b1e66996759b0253807b20a2ba6e2cb6b27221c789204

test:
  secret_key_base: c199946eace6f4c9a789c2da4caf732a68129e19de15e7307f255432d78114b752d3a97f9598928d0a15ac38f3301f55b23865e8d8e6ad316d6c897dee3a274c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
